name: Auto PR from Feature to Dev

on:
  push:
    branches:
      - feature

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated changes from feature branch"
        title: "Auto PR: Merge feature to dev"
        body: "This PR was created automatically when changes were pushed to the `feature` branch."
        base: dev
        branch: feature
        delete-branch: false
        draft: false

  auto-merge:
    needs: create-pull-request
    runs-on: ubuntu-latest

    steps:
    - name: Auto Merge PR
      uses: pascalgn/automerge-action@v0.15.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
