name: Deploy Power Platform Components

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to deploy'
        required: true
        default: ADCBMasterConfigurations

env:
  ENVIRONMENT_URL: 'https://demo001.crm8.dynamics.com/'
  CLIENT_ID: '2c34728a-634b-414c-b7e4-e904ead4b2c1'
  TENANT_ID: '807cb068-493f-40b4-b067-712d94fa7730'

permissions:
  contents: read

jobs:
  deploy-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Authenticate with Power Platform
        uses: microsoft/powerplatform-actions/authenticate@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ env.TENANT_ID }}

      - name: Pack Solution (WebResources, Flows, Plugins)
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-folder: powerplatform/${{ github.event.inputs.solution_name }}
          solution-file: powerplatform/${{ github.event.inputs.solution_name }}_unmanaged.zip
          solution-type: Unmanaged
          localize: false

      - name: Import Solution to Power Platform
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-file: powerplatform/${{ github.event.inputs.solution_name }}_unmanaged.zip
